#! /bin/sh

# 'full-status' first output is volume, second output is mute-status
vol=$(pulseaudio-ctl full-status | awk '{print $1}')
mute_status=$(pulseaudio-ctl full-status | awk '{print $2}')

case ${mute_status} in
    yes)
        icon=" " ;;
    no)
        icon=" " ;;
esac

echo "${icon} ${vol}%"
